### PR TITLE
Add NOT function

### PR DESCRIPTION
**Pull request by kmonson**
Pro tip: Don't use Libre Office Calc to make test spreadsheets. It munged everything into integers when I saved it. I have to bust out my work machine to make a proper test sheet to ensure proper behavior.

### CODE REVIEW

**Comment by kmonson** [comment]
Fixes #45

**Comment by kmonson** [comment]
@bradbase I hate to be that guy, but are you going to get back to this project any time soon?

**Comment by bradbase** [comment]
Hi @kmonson 

Apologies for leaving your PRs stranded.

From my perspective, you're fine being "that guy". Equally I don't want to be "that project owner" that leaves code stranded or unreleased.

**Comment by bradbase** [comment]
@kmonson Is there a way we can communicate outside github?

**Comment by kmonson** [comment]
> @kmonson Is there a way we can communicate outside github?

**Comment by kmonson** [comment]
> @kmonson Is there a way we can communicate outside github?

Sure, what do you have in mind?

I can do email, Discord or just about anything else reasonable. Carrier pigeon is right out, though. 

I can be reached at monson.kyle@gmail.com and we can go from there.

**Comment by strichter** [comment]
@kmonson if you fix the tests now that master tests are passing, I will make a release today with this PR merged.

**Comment by strichter** [comment]
Released in 0.4.0.

**Pull request merged**
