### PR TITLE
pass ignore_hidden from read_and_parse_archive to parse_archive

### PR DESCRIPTION
**Pull request by stanim**
Probably the diff is clear enough. Unfortunately Travis CI fails, but that is inherited from the master branch.

### CODE REVIEW

**Comment by bradbase** [comment]
Broken master.. Well crap.

**Comment by bradbase** [comment]
Thank you for your contribution.

This is kinda bizarre. tox on my machine says we are all good. In any case...

Seems the broken tests are WRT model.json. If that file doesn't get re-generated when the structure of the file change or when values get calculated differently tests should fail. Generating model.json is complex and needs to be done by hand. Setting up a test like that is not a very good thing for me to have done.

I'll attempt to fix things for Travis this week.

**Comment by bradbase** [comment]
Is super bizarre...

**Comment by bradbase** [comment]
Is super bizarre...

tox on Travis has used openpyxl==3.0.6 when the requirements file specifies 3.0.3.

`tox -r` on local machine is the key.

In any case openpyxl has moved on.

An important change in 3.0.6. numpy.float is deprecated.  np.float was removed from openpyxl/compat/numbers.py as np.float is now equivalent to float.

Another change is they've dropped dependency on jdcal in openpyxl==3.0.7

**Comment by strichter** [comment]
Released in 0.4.0.

**Pull request merged**
